### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by tissatussa** [shossjer/fimbulwinter#1]
hi, i just found your engine and i want to compile it but i did not succeed : using git clone over https gives errors : it demands some key to access and download files in a few subfolders .. but i managed to get the 5.05 version from the Jim Ablett archives and it runs fine in CuteChess !  And it has a nice refreshing style : i see with White it starts with the fianchetto position after 1.g3 2.Bg2 and 3.Nf3 which i never saw by any engine ! Are you still working on a newer version ? I like to compile it .. can you help ?
(I'm on Xubuntu 21.10)

**Comment by shossjer** [comment]
I think this is not the project you think it is
